SRCS_MATH	=	ft_abs.c \
				ft_find_next_prime.c \
				ft_is_prime.c \
				ft_max_min.c \
				ft_max_minf.c \
				ft_pow.c \
				ft_sqrt.c \
				ft_swap.c

FTST_MATH	=	ft_swap.ftst.c

MATH_DIR	= math/

SRCS += ${addprefix ${MATH_DIR}, ${SRCS_MATH}}
FTST += ${addprefix ${MATH_DIR}, ${FTST_MATH}}