LIST_SRCS	=	ft_create_elem.c \
				ft_list_at.c \
				ft_list_clear.c \
				ft_list_find.c \
				ft_list_foreach_if.c \
				ft_list_last.c \
				ft_list_merge.c \
				ft_list_push_back.c \
				ft_list_push_front.c \
				ft_list_remove_if.c \
				ft_list_reverse.c \
				ft_list_size.c \
				ft_list_sort.c

LIST_DIR	= data_structure/list/

SRCS += ${addprefix ${LIST_DIR}, ${LIST_SRCS}}