VEC_SRCS	=	ft_vec_create_reserv.c \
				ft_vec_create.c \
				ft_vec_destructor.c \
				ft_vec_fetch_array.c \
				ft_vec_pop_back.c \
				ft_vec_push_back.c \
				ft_vec_realloc.c \
				ft_vec_returndel.c

VEC_DIR		= data_structure/vector/

SRCS += ${addprefix ${VEC_DIR}, ${VEC_SRCS}}